[package]
name = "mux-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mux"
path = "src/main.rs"

[dependencies]
muxux-core = { path = "../core" }
cmx-utils = { path = "../../cmx-utils" }
serde_json = "1"
